### ISSUE TITLE
Xcode 13 beta 3 - SwiftPM - Build error: UIApplication.sharedApplication not available in iOS App Extension

### ISSUE THREAD

**Issue by klanchman** [SiftScience/sift-ios#100]
When building an app with Sift from Swift Package Manager in Xcode 13 beta 3 that _does not_ use app extensions, compiler errors related to API availability in app extensions are emitted.

### Reproduction Steps

- Create a new iOS project in Xcode 13 beta 3
- Add Sift at latest version (2.0.3) using Swift Package Manager
- Build the app

Result: multiple errors on `UIApplication.sharedApplication` usage:

```
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
```

### Other Notes

This appears to be expected behavior in Xcode 13 beta 3 with Swift Package Manager, based on this [Apple Developer Forums thread](https://developer.apple.com/forums/thread/685103) and this [Swift forums post](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11). The Apple engineer in the second link recommends dealing with this by marking declarations as unavailable to app extensions when they use APIs that are unavailable to app extensions.

***

**Update**: It looks like the Swift team is [reconsidering how this behaves](https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/32). I'll update this issue as we hear more from them.

**Comment by mthole** [comment]
I am running into this as well.

**Comment by vincent-sift** [comment]
This issue has been fixed with the latest release https://github.com/SiftScience/sift-ios/releases/tag/v2.0.4
