### ISSUE TITLE
Switching between Sandbox

### ISSUE THREAD

**Issue by orafaaraujo** [SiftScience/sift-ios#110]
Hi,

In my app, I have a feature to switch between environments (prod, dev, qa etc). When doing this I would like to switch Sift between Prod and Sandbox.

Is calling setup again enough? Should I do something more than that?
```swift
let sift = Sift.sharedInstance
sift()?.accountId = accountId
sift()?.beaconKey = beaconKey
```

Thank you in advance

**Comment by viaskal-sift** [comment]
@orafaaraujo sorry, this was definitely an oversight. Yes, changing `account_id` and `beaconKey` should be enough to switch between the envs
