### ISSUE TITLE
Value of type 'Sift?' has no member 'allowUsingMotionSensors'

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [SiftScience/sift-ios#113]
Version 2.1.1 seems to have removed the option to allow using motion sensors?

`Sift.sharedInstance().allowUsingMotionSensors = true`

**Comment by vincent-sift** [comment]
Correct @jordanhbuiltbyhq this is data that we no longer collect and thus we have removed it from our iOS SDK.

**Comment by jordanhbuiltbyhq** [comment]
Ok thanks! You may want to remove that from the README then and maybe not it in the changelog? ;)

**Comment by vincent-sift** [comment]
Thanks for letting us know, we will update the README and changelog.
