### ISSUE TITLE
Sift does not compile in Xcode 14.3 RC - file not found

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [SiftScience/sift-ios#118]
Trying to run our app on the Simulator in Xcode 14.3 RC shows this buildtime error:

> File not found: /Applications/Xcode14.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

Looking into it I can see there is no arc folder there in Xcode 14.3 unlike Xcode 14.2.

Note we integrated Sift (2.1.1) via CocoaPods. Our app's deployment target is iOS 16. Using macOS Ventura 13.2.1.

<img width="1378" alt="Screenshot 2023-03-23 at 1 32 17 PM" src="https://user-images.githubusercontent.com/15804476/227329470-f9a8a25d-65aa-4a71-b5c5-4ba9760c1659.png">

If after running `pod install` you upgrade to the recommended project settings, it seems to resolve this issue, however issue #116 returned:

> /.../Pods/Target Support Files/Sift/Sift-umbrella.h:13:9 double-quoted include "SiftCompatibility.h" in framework header, expected angle-bracketed instead

**Comment by dineybomfim** [comment]
Everybody with the newst Xcode seems to be blocked from even generating archives due to it... so we're blocked on TestFlight and AppStore.
Need to release a new app version but can't until this is fixed.

**Comment by viaskal-sift** [comment]
@jordanhbuiltbyhq @dineybomfim sorry for the delay, we are already taking a look at the issue, so hopefully will introduce a fix soon

**Comment by viaskal-sift** [comment]
@jordanhbuiltbyhq @dineybomfim is the issue is still valid? cc @SujishaExalture

**Comment by jordanhbuiltbyhq** [comment]
Testing with Sift 2.1.2 in Xcode 14.3.1 I can confirm this issue still remains.

1. `pod install`
2. Run the app
Under Sift:
Error: `File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a`
Warning: `/Users/Jordan/Developer/AppName/Pods/Pods.xcodeproj The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 11.0 to 16.4.99.`
Error: `Linker command failed with exit code 1 (use -v to see invocation)`
3. Click the "Update to recommended settings" warning
4. Click "Perform Changes"
5. Run the app
8 errors appear:
<img width="414" alt="Screenshot 2023-07-12 at 9 15 31 AM" src="https://github.com/SiftScience/sift-ios/assets/15804476/c6106cbc-2d90-4700-ad7f-b8bbca11d69c">

Note if you deselect "Target 'Sift' - Enable Module Verifier" and leave the other 3 Sift items selected (and all other items for other dependencies) then it works without issue.

**Comment by SujishaExalture** [comment]
@jordanhbuiltbyhq  The minimum deployment target we set to 12 for SIFT 2.12.                                                                              With Xcode 14.3 , No such build errors .  We will check with 14.3.1 also and will update soon. 

<img width="1314" alt="Screenshot 2023-07-13 at 2 19 44 PM" src="https://github.com/SiftScience/sift-ios/assets/6427703/9b737130-6b76-4ba1-8d24-28543cb39335">

**Comment by jordanhbuiltbyhq** [comment]
Following the steps the minimum deployment is not 12.0 it's 8.0.
<img width="1030" alt="Screenshot 2023-07-13 at 10 33 42 AM" src="https://github.com/SiftScience/sift-ios/assets/15804476/9580b7e4-6db6-4159-aa4f-998aff39a9d1">

**Comment by viaskal-sift** [comment]
@jordanhbuiltbyhq is it solved in the latest version (2.1.5)?

**Comment by jordanhbuiltbyhq** [comment]
Yes thank you
