### ISSUE TITLE
Sift-ios repository no longer pullable due to sub-module absence. 

### ISSUE THREAD

**Issue by JosephHedges** [SiftScience/sift-ios#125]
Issue: Due to a repository link in /samples/HackerNewsReader pointing to SiftScience/HackerNewsReader which no longer exists, the sub-module pull task now fails.

Remedy:  Remove link to defunct sample repository.

**Comment by bruno-machado-utility** [comment]
👍 
Facing the same issue

**Comment by wlyonsRR** [comment]
We are having the same issues.

**Comment by anwuna** [comment]
I am currently facing the same issue where my app build is failing due to SPM's inability to resolve the package graph correctly. Is there any information available regarding a potential fix for this issue in the near future?

**Comment by mpierotti-sift** [comment]
Thanks for reporting this. This reference has been removed as part of this PR: https://github.com/SiftScience/sift-ios/pull/126

**Comment by keagan** [comment]
doesn't seem to have fixed the problem? does there need to be a new version published?
