### ISSUE TITLE
sift-ios fails to resolve package dependencies, using SPM

### ISSUE THREAD

**Issue by adam-z** [SiftScience/sift-ios#128]
Ever since this commit was merged to master, all clean builds fail when attempting to resolve package dependencies:

I've tested on release 2.1.2, release 2.1.1 and get the following error:
```
Couldn't update repository submodules:
    Submodule 'samples/HackerNewsReader' (https://github.com/SiftScience/HackerNewsReader.git) registered for path 'samples/HackerNewsReader'
    Cloning into '/[redacted-path]/SourcePackages/checkouts/sift-ios/samples/HackerNewsReader'...
    fatal: could not read Username for 'https://github.com/': terminal prompts disabled
    fatal: clone of 'https://github.com/SiftScience/HackerNewsReader.git' into submodule path '/[redacted-path]/SourcePackages/checkouts/sift-ios/samples/HackerNewsReader' failed
```

I've also tested by pointing the sift-ios package directly at the latest master commit hash: `ae4abc1e85fb7371e7cdcd2d80efeb10776735d1` Doing so produces the following error:

```
Checking out ae4abc1e85fb7371e7cdcd2d80efeb10776735d1 of package ‘sift-ios’
Couldn’t update repository submodules:
    fatal: No url found for submodule path 'samples/HackerNewsReader' in .gitmodules
```

**Comment by adam-z** [comment]
Also note: build failures on our CI/CD pipeline actually started today around 3:15 PM, so likely the issue with the HackerNewReader repo at that time.

**Comment by njolly-sift** [comment]
Hi @adam-z - We have rectified the original issue reported and you can now rebuild the app with the previous version 2.1.2

**Comment by adam-z** [comment]
Hey @njolly-sift 

Thank you for the swift response! I am testing out the build out now with version 2.1.2, and it seems to be working both locally and on the CI setup.

**Comment by dbarden** [comment]
We're still facing this issue with 2.1.3

The weird thing is that pointing to `master` works, while pointing to `2.1.3` throws an error of:

```
Showing All Errors Only

sift-ios

Checking out 2.1.3
Couldn’t update repository submodules:
    fatal: No url found for submodule path 'samples/HackerNewsReader' in .gitmodules
Couldn’t update repository submodules:
```

Also, when I run

`git submodule status`, I get:

> fatal: no submodule mapping found in .gitmodules for path 'samples/HackerNewsReader'

I'll try and send a PR totally removing the samples directory, if that's ok :)
