### ISSUE TITLE
Privacy Manifest Support

### ISSUE THREAD

**Issue by J-Mendes** [SiftScience/sift-ios#137]
Apple introduced at the WWDC 2023 the [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests). This makes it easy for developers to report the data SDKs collect to Apple.

> Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect. Your app’s privacy manifest file doesn’t need to cover data collected by third-party SDKs that your app links to.

It would be great, if Sift could add a Privacy Manifest that reports the data, which is collected by the framework. Are you considering support this? If so do you have a timeline on when?

**Comment by viaskal-sift** [comment]
@J-Mendes thanks for raising this, we are actually working on this already, and can provide it soon

**Comment by viaskal-sift** [comment]
@J-Mendes you should be able to find the file in a new version (2.1.6). If everything is ok - feel free to close the issue. Thanks!

**Comment by J-Mendes** [comment]
@viaskal-sift I was checking the file and it seems that it's not following the privacy manifest format where you need to specify by data type the apis usage and reasons. You can check the documentation about the correct format [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests). Thanks!

**Comment by GMCristiano** [comment]
Is there a plan to fix the file?

**Comment by viaskal-sift** [comment]
@GMCristiano yes, we are working on it, I will let you know right after this issue is addressed

**Comment by viaskal-sift** [comment]
@J-Mendes @GMCristiano we plan to ship the following PR - https://github.com/SiftScience/sift-ios/pull/143, if you could take a look that would be great. Thanks!

**Comment by J-Mendes** [comment]
Hi @viaskal-sift I was reviewing that PR and I think since you're using the `lstat` method the `NSPrivacyAccessedAPITypes` is missing with the `NSPrivacyAccessedAPICategoryFileTimestamp` and `NSPrivacyAccessedAPICategorySystemBootTime` api types, [as Apple states on the documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393).

These keys should be removed from the root and instead use the following format:
```
<dict>
<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryFileTimestamp</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>C617.1</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategorySystemBootTime</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>35F9.1</string>
			</array>
		</dict>
	</array>

	...

</dict>
```

**Comment by adysart** [comment]
+1 to @J-Mendes. The existing PrivacyInfo.xcprivacy file is not in the correct format.

**Comment by MartinMobile** [comment]
When updating the SDK I could not see that the .xcprivacy file in the pod folder. 
Think you need to add .xcprivacy file to the pod spec like this
`s.resource_bundles = {"Sift" => ["PrivacyInfo.xcprivacy"]}`

**Comment by SreelekhN** [comment]
@J-Mendes 
<img width="1125" alt="Screenshot 2024-03-25 at 3 38 59 PM" src="https://github.com/SiftScience/sift-ios/assets/46746027/c1f2212c-ee02-4b99-a738-83494f0d401d">

I think this is the right format, can you confirm ?

**Comment by J-Mendes** [comment]
@SreelekhN Yes, it looks to be the right format 💪 I'm just not sure if the File Timestamp reason should be DDA9.1 or C617.1

**Comment by SreelekhN** [comment]
@J-Mendes here is a pr made for the above issue.
https://github.com/SiftScience/sift-ios/pull/144

Can u verify if everything is ok.

**Comment by djs-code** [comment]
@SreelekhN  We're on SPM, and no dice for me.  I believe you need to add the following to the `sift-ios` target in your `Package.swift`:

`resources: [.process("PrivacyInfo.xcprivacy")],`

**Comment by dbarden** [comment]
Here it is: https://github.com/SiftScience/sift-ios/pull/146/files

**Comment by MartinMobile** [comment]
Hey @viaskal-sift Will there be a release with this PR soon, I am eager to get this manifest thing out of the way  :)

**Comment by viaskal-sift** [comment]
@MartinMobile yes, I will push for the review, and we will release right after it is approved

**Comment by MartinMobile** [comment]
But it seems to already be in main and released with https://github.com/SiftScience/sift-ios/releases/tag/v2.1.8 ? 
Or am I confusing myself?

**Comment by viaskal-sift** [comment]
@MartinMobile ah yes, if you mean the current issue - then yes, it has been already merged and released. I thought you were asking about this follow-up improvement - https://github.com/SiftScience/sift-ios/pull/146/files

**Comment by SreelekhN** [comment]
> @SreelekhN We're on SPM, and no dice for me. I believe you need to add the following to the `sift-ios` target in your `Package.swift`:
> 
> `resources: [.process("PrivacyInfo.xcprivacy")]`
<img width="298" alt="Screenshot 2024-04-18 at 3 48 18 PM" src="https://github.com/SiftScience/sift-ios/assets/46746027/547745dc-d3df-4c75-9f56-7ee3f35bd429">


the file is available via spm, i tried it in a new project and its appeaing

**Comment by johnnywang** [comment]
I see that some of the API accesses are listed as used for tracking (i.e. user id, device id): does that not mean that the privacy tracking needs to be set to true, and the tracking domains specified as well?

**Comment by vijaytholpadi** [comment]
@SreelekhN the file showing up in the screenshot does not mean it is available in the package. You screenshot only shows the files that are present on the file system. Not necessarily in the package.

We need to add `resources: [.process("PrivacyInfo.xcprivacy")]` to the SPM definition to get the privacy manifest to be included as part of the package.

**Comment by viaskal-sift** [comment]
@J-Mendes the issue shoud have been fixed already, are you okay with closing this one?
