### ISSUE TITLE
how to validate integration

### ISSUE THREAD

**Issue by chrischen-eatnow** [SiftScience/sift-ios#50]
hi there, after integrated Sift Science iOS SDK, how do I verify it's been successfully integrated? I tried looking into the Developer area on the web portal, couldn't get a clue

**Comment by megamannn** [comment]
Hello there! 

So if you go to the Developer tab in the console, click on API logs, and change the event filter to "Mobile Events" you'll see all the logs for mobile events, allowing you to verify the SDK has been successfully integrated. (Here's a screenshot from our test account):

<img width="627" alt="screen shot 2016-11-17 at 4 55 44 pm" src="https://cloud.githubusercontent.com/assets/16088357/20414334/ce460c36-ace6-11e6-8c7f-c19d20ae5a62.png">


(_Separately, I checked out your integration and it looks like you have a couple errors. If you have any questions on these errors/would like to work with our solutions engineers, feel free to email support@siftscience.com_)

**Comment by chrischen-eatnow** [comment]
thanks, this issue can be closed
