### ISSUE TITLE
App crashes if Sift was initialized after keyboard was shown.

### ISSUE THREAD

**Issue by yevheniyZaychenko** [SiftScience/sift-ios#56]
**Steps to reproduce:**

1. Open keyboard or trigger system alert, whatever, we need UIApplication.sharedApplication.windows to has more than 1 UIWindow.
2. Initialize Sift.
3. Try to close keyboard or system alert.
 -> Crash;

This crash happens due to KVO observing:

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7f7ffae54960 of class UIRemoteKeyboardWindow was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x6000006206a0> (
<NSKeyValueObservance 0x600000645670: Observer: 0x6000000fe700, Key path: rootViewController, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x600000644b90>
)'
`

I've made some research inside Sift library and found next: (class SFlosAppStateCollector.m)

`NSString *rootViewControllerKeyPath = NSStringFromSelector(@selector(rootViewController));
        for (UIWindow *window in UIApplication.sharedApplication.windows) {
            [window addObserver:self forKeyPath:rootViewControllerKeyPath options:0 context:nil];
        }`

After this action if any of UIWindows are deallocated we receive a crash.

Tested on iOS 10.3.1 with latest Sift version 0.9.4.

Thanks.

**Comment by garylee1** [comment]
@yevheniyZaychenko  – We've released v0.9.5, which hopefully fixes this. Please try it out when you get the chance and let us know what the results are. Thanks again for surfacing the crash.

**Comment by yevheniyZaychenko** [comment]
@garylee1 , it seems that this issue was fixed, Thank you!
