### ISSUE TITLE
SFUploader.m: 'NSData+GZIP.h' file not found

### ISSUE THREAD

**Issue by edenman** [SiftScience/sift-ios#57]
I have to change 
```
#import "NSData+GZIP.h"
```
to
```
#import "Vendor/NSData+GZIP.h"
```
to get the pod to compile.  Not that big a deal, but seems like something is broken in your pod packaging?

Sift pod version 0.9.4
swift 3 (although it happens on 2.3 too)
Xcode 8.3.1

**Comment by garylee1** [comment]
Thanks for surfacing this @edenman – we've added your fix to an upcoming release and will let you know when it's out.

**Comment by garylee1** [comment]
@edenman – We've released v0.9.5, which incorporates your fix. Thanks again and let me know once you've confirmed it works!

**Comment by edenman** [comment]
Sorry, totally forgot about this.  It's fixed in 0.9.5, thanks!
