### ISSUE TITLE
Crash in SFQueue.m line 131

### ISSUE THREAD

**Issue by insidegui** [SiftScience/sift-ios#63]
We're seeing hundreds of crashes on Fabric in SFQueue.m line 131.

[Here's the crash log](https://github.com/SiftScience/sift-ios/files/1102425/sfqueue_crash.txt)

Looks like the issue that's causing the crash is:
```
Fatal Exception: NSInvalidArgumentException
-[__NSMallocBlock__ count]: unrecognized selector sent to instance 0x170c53350
```

Let me know if you need any additional information.

**Comment by clchiou** [comment]
The crash report shows stack traces of `checkUploadReadinessLater`. And
from the recent git logs it looks like that method was removed at v0.9.2 to
fix a race condition bug. What's the version of SDK you are using?

**Comment by insidegui** [comment]
Can you confirm that the latest version also fixes #59 ? We had to resort to a workaround for that and I can't risk bringing that crash back.

**Comment by clchiou** [comment]
Sorry I don't work for Sift and don't have the answer for that question.

**Comment by garylee1** [comment]
@insidegui I can confirm that the latest release addresses this issue as well as #59
