### ISSUE TITLE
Crash calling UI API on background thread

### ISSUE THREAD

**Issue by bmetitiri** [SiftScience/sift-ios#68]
I'm getting a crash coming from Sift when calling `doUpload` in the `SFUploader`. Xcode says that `UIApplication.sharedApplication.applicationState` can only be accessed of the main thread.

**Comment by quanpod** [comment]
Thanks @bmetitiri for the report - what version of the iOS SDK are you using?  We've seen this issue in the past as we were updating the SDK for iOS 11.  The latest version has that fix in it if you're using an older version.

**Comment by bmetitiri** [comment]
Interesting, I updated my cocoapods and it claimed I was on 0.9.10, but looking at the source file, it definitely doesn't include the last couple commits that fixed this. I removed my pods and did a clean install and now I have the latest and it's working fine, so looks like a cocoapod issue. Sorry for the unnecessary issue.

**Comment by quanpod** [comment]
No worries @bmetitiri, we're happy to help!
