### ISSUE TITLE
SFTokenBucket class collides with an Apple Private Class

### ISSUE THREAD

**Issue by fbartho** [SiftScience/sift-ios#79]
```
objc[71561]: Class SFTokenBucket is implemented in both /Applications/Xcode-10.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/Sharing.framework/Sharing (0x1287ed228) and /Users/fbarthelemy/Library/Developer/Xcode/DerivedData/TRClient-gzzcmjoochuykxgkrnwnsjhgriqb/Build/Products/Release-iphonesimulator/Sift.framework/Sift (0x10f792340). One of the two will be used. Which one is undefined.
```

**Comment by fbartho** [comment]
Apple reserves 2-letter Class Prefixes in Objective-C, so it might be safer to rename all SF* prefixed classes to SSF? -- not sure how you want to handle this.

**Comment by fbartho** [comment]
Also, when you add a category like `NSData (Gzip)`, you need prefix all the methods so they don't collide with client libraries. :(

**Comment by fbartho** [comment]
This article: https://nshipster.com/namespacing/ gives some background.
This article: https://nshipster.com/at-compiler-directives/ explains `@compatibility_alias` which might be useful here!

**Comment by aaronTufts** [comment]
Hi @fbartho, thanks for all the context here and sorry for the delay. We'll take a look at this over the next few days and then update to let you know our plan.

Any info you have on the impact on and frequency of affected users would be helpful.  Have a good weekend.

**Comment by fbartho** [comment]
Sorry, because of this kind of collision, I can’t guarantee that we would get accurate crashlogs.

I do not have an estimate on how much this is happening in the wild. I also unfortunately can’t provide a reliable reproduction case. 

My advice is entirely based on general best practices for Objective-C development on iOS — hopefully helping us catch this before it becomes an urgent problem!

**Comment by shepting** [comment]
@aaronTufts We are seeing this warning occur 20% of the time in our CI jobs.

**Comment by geoffnix** [comment]
I am seeing this warning also

**Comment by aaronTufts** [comment]
Thanks for sharing the info everyone. We're taking a look.

**Comment by kikettas** [comment]
Is there any plans on solving this issue?

**Comment by aaronTufts** [comment]
Apologies for no update. We're looking to address in our next couple of sprints.

**Comment by aaronTufts** [comment]
Hi all, thanks for your patience here. We're starting work on this in our next sprint, which starts Monday.

**Comment by pjain-sift** [comment]
Fix for this issue has been released with v2.0.0. on 02/24/2020. Please refer to change log for more details. Keeping this ticket open for few days for any post release issues.

**Comment by fbartho** [comment]
@pjain-sift -- it looks like the 2.0.0 release isn't fully marked as the latest release?
<img width="977" alt="image" src="https://user-images.githubusercontent.com/209712/75204011-8e88f180-5724-11ea-94ef-dde1dd6146f5.png">

(The code we use to update our dependency relies on the Github Releases page)

**Comment by pjain-sift** [comment]
> @pjain-sift -- it looks like the 2.0.0 release isn't fully marked as the latest release?
> <img alt="image" width="977" src="https://user-images.githubusercontent.com/209712/75204011-8e88f180-5724-11ea-94ef-dde1dd6146f5.png">
> 
> (The code we use to update our dependency relies on the Github Releases page)

Done.

**Comment by fbartho** [comment]
Thanks @pjain-sift -- we have a PR to update our app with the new version, and at a first approximation it compiled! -- That said, we won't be able to properly test until later this week. I didn't want to leave you waiting for more immediate feedback!
