### ISSUE TITLE
Build Warnings under Xcode 11

### ISSUE THREAD

**Issue by fbartho** [SiftScience/sift-ios#82]
There are a ton of Build Warnings when using Sift with Xcode 11. Xcode 11 is going to be required (because iOS SDK 13 is going to be required) in Early April.

It'd be lovely if sift-ios could be updated to be warning free. Most of the warnings seem very minor, and easy to update.

**Comment by pjain-sift** [comment]
@fbartho At my end, I see 50 warnings for Sift iOS SDK framework. Please see attached GIF. Are warnings count same at your end as well?

![iOS_SDK_Warning_Gif](https://user-images.githubusercontent.com/59588493/75366490-aae77400-5873-11ea-8b8d-9b1c7b2b5ceb.gif)

**Comment by fbartho** [comment]
I think that’s right!

**Comment by pjain-sift** [comment]
@fbartho This has been released with version v2.0.1 , let me know if you need anything else. Please close the ticket if you find everything ok!

**Comment by aaronTufts** [comment]
Closing. Please reopen if you see a further issue here.
