### ISSUE TITLE
nicklockwood/GZIP should be pulled as a dependency, instead of copied to this library

### ISSUE THREAD

**Issue by gsabran** [SiftScience/sift-ios#91]
[Sift/Vendor](https://github.com/SiftScience/sift-ios/tree/master/Sift/Vendor) should be pulled as project dependencies instead of copied in this library. This causes issues when also using the original library as the same code exists twice.

Both SPM and Cocoapod should allow to do this.

**Comment by viaskal-sift** [comment]
Resolved in 2.0.0 version
